name: authentication_repository
description: package to manage the authentication domain layer.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies: 
  equatable: ^2.0.5 
  firebase_auth: ^3.11.2 
  firebase_core: ^1.24.0 
  google_sign_in: ^5.4.2 
  meta: ^1.7.0
    
dev_dependencies: {mocktail: ^0.3.0, plugin_platform_interface: ^2.1.3, test: ^1.21.1, very_good_analysis: ^3.0.2,}
